### ISSUE TITLE
Quickly jump to the corresponding page

### ISSUE THREAD

**Issue by thunderbolt-fire** [freddyaboulton/gradio-pdf#15]
![image](https://github.com/user-attachments/assets/e7b2c724-e176-4966-88f1-d86edea3c612)

Thanks for your work. How do I change the page number to jump ? This can help quickly find the need page.

**Comment by philsv** [comment]
@thunderbolt-fire should be possible with PDF(starting_page=24)

**Comment by thunderbolt-fire** [comment]
> @thunderbolt-fire should be possible with PDF(starting_page=24)

Thanks,I want to achieve that I can change  directly the number at the interface.
![image](https://github.com/user-attachments/assets/82191537-08a5-44b4-9841-be1059637158)

**Comment by freddyaboulton** [comment]
Yes should be possible

**Comment by thunderbolt-fire** [comment]
> Yes should be possible

My meaning is that change the number at the front end rather than the back end.

**Comment by antoine-mle** [comment]
> Yes should be possible

You mean it could be available in a future release? Interested as well!
Thanks for the quick fix [solution](https://huggingface.co/spaces/freddyaboulton/gradio_pdf/discussions/4) in the meantime by the way 😉

**Comment by freddyaboulton** [comment]
Yes will work on native support for this soon. Should be pretty straightforward though if anyone would like to work on a PR in the meantime.

**Comment by freddyaboulton** [comment]
Fixed in version 0.0.14!

**Comment by antoine-mle** [comment]
Hi @freddyaboulton, 

Many thanks for the version upgrade and having looked at this issue!
I unfortunately still see a little bug as the last digit does not appear anymore if the page number exceed 3 digits. See below an example, if I move from page 99 to page 100, in the latter stage it displays page "10" instead of "100".

<img width="642" alt="Capture d’écran 2024-09-06 à 04 24 54" src="https://github.com/user-attachments/assets/fef252bf-e797-4b3e-8878-ab21e1abd033">
<img width="631" alt="Capture d’écran 2024-09-06 à 04 25 02" src="https://github.com/user-attachments/assets/5c501014-5f34-414f-9758-bb9bcf7b3432">

**Comment by freddyaboulton** [comment]
Fixed in version 0.0.15!

![large_pdf_pages_error](https://github.com/user-attachments/assets/c8e1a50b-dbe1-4d5f-9d48-0e1266c86e72)
